/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.11 and the Signal Processing Toolbox 6.14.
 *
 * Generated on: 21-Oct-2011 15:13:40
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 33
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\Program Files\MATLAB\R2010b\extern\include\tmwtypes.h 
 */
const int BL = 33;
const real64_T B[33] = {
  -0.001516349738389,2.081554061972e-018, 0.002491479921628,-0.002271146009083,
  -0.003353937731098, 0.007841945837854,-8.527967107065e-018, -0.01517220634899,
    0.01265160164161,   0.0168618819134, -0.03619195143682,1.86405770045e-017,
    0.06560253013782, -0.05763357604925, -0.09043407821594,   0.3005894140548,
      0.601068784045,   0.3005894140548, -0.09043407821594, -0.05763357604925,
    0.06560253013782,1.86405770045e-017, -0.03619195143682,   0.0168618819134,
    0.01265160164161, -0.01517220634899,-8.527967107065e-018, 0.007841945837854,
  -0.003353937731098,-0.002271146009083, 0.002491479921628,2.081554061972e-018,
  -0.001516349738389
};
