# FIXED
McBSP_DMA.obj: ../source/McBSP_DMA.c
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_Device.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_Adc.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_DevEmu.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_CpuTimers.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_ECan.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_ECap.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_DMA.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_EPwm.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_EQep.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_Gpio.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_I2c.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_McBSP.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_PieCtrl.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_PieVect.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_Spi.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_Sci.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_SysCtrl.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_XIntrupt.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_Xintf.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_Examples.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_GlobalPrototypes.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_ePwm_defines.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_Dma_defines.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_I2C_defines.h
McBSP_DMA.obj: F:/workspace1/lab24-McBSP_DMA/include/DSP2833x_DefaultISR.h
