# FIXED
ExInt.obj: ../SRC/ExInt.c
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_Device.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_Adc.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_DevEmu.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_CpuTimers.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_ECan.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_ECap.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_DMA.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_EPwm.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_EQep.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_Gpio.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_I2c.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_McBSP.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_PieCtrl.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_PieVect.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_Spi.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_Sci.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_SysCtrl.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_XIntrupt.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_Xintf.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_Examples.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_GlobalPrototypes.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_ePwm_defines.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_Dma_defines.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_I2C_defines.h
ExInt.obj: F:/workspace1/lab5-External_Interrupt_button/INCLUDE/DSP2833x_DefaultISR.h
