# FIXED
Spi_lookback.obj: ../SRC/Spi_lookback.c
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_Device.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_Adc.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_DevEmu.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_CpuTimers.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_ECan.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_ECap.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_DMA.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_EPwm.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_EQep.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_Gpio.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_I2c.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_McBSP.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_PieCtrl.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_PieVect.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_Spi.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_Sci.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_SysCtrl.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_XIntrupt.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_Xintf.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_Examples.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_GlobalPrototypes.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_ePwm_defines.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_Dma_defines.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_I2C_defines.h
Spi_lookback.obj: F:/workspace1/lab21-SPI_LOOKBACK_INT/INCLUDE/DSP2833x_DefaultISR.h
