# FIXED
HRPWM_SFO.obj: ../source/HRPWM_SFO.c
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_Device.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_Adc.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_DevEmu.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_CpuTimers.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_ECan.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_ECap.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_DMA.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_EPwm.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_EQep.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_Gpio.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_I2c.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_McBSP.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_PieCtrl.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_PieVect.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_Spi.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_Sci.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_SysCtrl.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_XIntrupt.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_Xintf.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_Examples.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_GlobalPrototypes.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_ePwm_defines.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_Dma_defines.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_I2C_defines.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/DSP2833x_DefaultISR.h
HRPWM_SFO.obj: F:/workspace1/lab29-HRPWM_SFO/include/SFO.h
