# FIXED
LED.obj: ../SRC/LED.c
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_Device.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_Adc.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_DevEmu.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_CpuTimers.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_ECan.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_ECap.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_DMA.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_EPwm.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_EQep.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_Gpio.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_I2c.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_McBSP.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_PieCtrl.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_PieVect.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_Spi.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_Sci.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_SysCtrl.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_XIntrupt.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_Xintf.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_Examples.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_GlobalPrototypes.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_ePwm_defines.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_Dma_defines.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_I2C_defines.h
LED.obj: F:/workspace1/lab1-GPIO_output_LED/INCLUDE/DSP2833x_DefaultISR.h
