# FIXED
McBSP_LOOKBACK_INT.obj: ../source/McBSP_LOOKBACK_INT.c
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_Device.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_Adc.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_DevEmu.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_CpuTimers.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_ECan.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_ECap.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_DMA.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_EPwm.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_EQep.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_Gpio.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_I2c.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_McBSP.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_PieCtrl.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_PieVect.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_Spi.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_Sci.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_SysCtrl.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_XIntrupt.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_Xintf.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_Examples.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_GlobalPrototypes.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_ePwm_defines.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_Dma_defines.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_I2C_defines.h
McBSP_LOOKBACK_INT.obj: F:/workspace1/lab23-McBSP_LOOKBACK_INT/include/DSP2833x_DefaultISR.h
