# FIXED
diskio.obj: ../SRC/diskio.c
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/diskio.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/integer.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/sdio_sd.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_Device.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_Adc.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_DevEmu.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_CpuTimers.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_ECan.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_ECap.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_DMA.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_EPwm.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_EQep.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_Gpio.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_I2c.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_McBSP.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_PieCtrl.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_PieVect.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_Spi.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_Sci.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_SysCtrl.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_XIntrupt.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_Xintf.h
diskio.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/SD.h
