# FIXED
disk_sd.obj: ../SRC/disk_sd.c
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/sdio_sd.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_Device.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_Adc.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_DevEmu.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_CpuTimers.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_ECan.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_ECap.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_DMA.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_EPwm.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_EQep.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_Gpio.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_I2c.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_McBSP.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_PieCtrl.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_PieVect.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_Spi.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_Sci.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_SysCtrl.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_XIntrupt.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_Xintf.h
disk_sd.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/SD.h
