# FIXED
SD_SPI_Registers.obj: ../SRC/SD_SPI_Registers.c
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/SD.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_Device.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_Adc.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_DevEmu.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_CpuTimers.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_ECan.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_ECap.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_DMA.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_EPwm.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_EQep.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_Gpio.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_I2c.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_McBSP.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_PieCtrl.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_PieVect.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_Spi.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_Sci.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_SysCtrl.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_XIntrupt.h
SD_SPI_Registers.obj: F:/workspace1/lab10-SD-SPI-Fatfs/INCLUDE/DSP2833x_Xintf.h
