# FIXED
Watchdog.obj: ../source/Watchdog.c
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_Device.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_Adc.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_DevEmu.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_CpuTimers.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_ECan.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_ECap.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_DMA.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_EPwm.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_EQep.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_Gpio.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_I2c.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_McBSP.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_PieCtrl.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_PieVect.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_Spi.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_Sci.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_SysCtrl.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_XIntrupt.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_Xintf.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_Examples.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_GlobalPrototypes.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_ePwm_defines.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_Dma_defines.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_I2C_defines.h
Watchdog.obj: F:/workspace1/lab12-WATCHDOG/include/DSP2833x_DefaultISR.h
