# FIXED
Example_EPwmSetup.obj: ../SRC/Example_EPwmSetup.c
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_Device.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_Adc.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_DevEmu.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_CpuTimers.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_ECan.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_ECap.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_DMA.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_EPwm.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_EQep.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_Gpio.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_I2c.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_McBSP.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_PieCtrl.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_PieVect.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_Spi.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_Sci.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_SysCtrl.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_XIntrupt.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_Xintf.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_Examples.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_GlobalPrototypes.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_ePwm_defines.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_Dma_defines.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_I2C_defines.h
Example_EPwmSetup.obj: F:/workspace1/lab20-PWM-CAP/INCLUDE/DSP2833x_DefaultISR.h
