# FIXED
main.obj: ../SRC/main.c
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_Device.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_Adc.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_DevEmu.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_CpuTimers.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_ECan.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_ECap.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_DMA.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_EPwm.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_EQep.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_Gpio.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_I2c.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_McBSP.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_PieCtrl.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_PieVect.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_Spi.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_Sci.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_SysCtrl.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_XIntrupt.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_Xintf.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_Examples.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_GlobalPrototypes.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_ePwm_defines.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_Dma_defines.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_I2C_defines.h
main.obj: F:/workspace1/lab2-GPIO_input_button/INCLUDE/DSP2833x_DefaultISR.h
