# FIXED
ADC_SOC_INT.obj: ../source/ADC_SOC_INT.c
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_Device.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_Adc.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_DevEmu.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_CpuTimers.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_ECan.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_ECap.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_DMA.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_EPwm.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_EQep.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_Gpio.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_I2c.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_McBSP.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_PieCtrl.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_PieVect.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_Spi.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_Sci.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_SysCtrl.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_XIntrupt.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_Xintf.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_Examples.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_GlobalPrototypes.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_ePwm_defines.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_Dma_defines.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_I2C_defines.h
ADC_SOC_INT.obj: F:/workspace1/lab26-ADC_SOC_INT/include/DSP2833x_DefaultISR.h
